name: "user_srv"

user_srv:
    ip: "192.168.56.1"
    port: 50001

mysql:
    host: "127.0.0.1"
    port: "3306"
    db: "buy3_user_srv"
    user: "root"
    password: "123456"

consul:
    host: "127.0.0.1"
    port: "8500"
